CREATE TABLE [dbo].[EXCHANGE_RATES] (
    [FROM_CURRENCY] VARCHAR (3)     NOT NULL,
    [TO_CURRENCY]   VARCHAR (3)     NOT NULL,
    [DATE]          DATE            NOT NULL,
    [EXCHANGE_RATE] DECIMAL (12, 6) NOT NULL,
    [INPUT_DATE]    DATETIME        CONSTRAINT [DF_EXCHANGE_RATES_INPUTDATE] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_EXCHANGE_RATES_DATE_FROMCURRENCY_TOCURRENCY] PRIMARY KEY CLUSTERED ([DATE] DESC, [FROM_CURRENCY] ASC, [TO_CURRENCY] ASC) WITH (FILLFACTOR = 90)
);

