

CREATE VIEW [dbo].[VW_EXCHANGE_RATES_USD_MISSING_DATES]
AS
SELECT
	CAST(c.DATE AS VARCHAR(10)) AS DATE,
	CAST(ISNULL(r.FROM_CURRENCY, '-') AS VARCHAR(10)) as FROM_CURRENCY,
	CAST(ISNULL(r.TO_CURRENCY, '-') AS VARCHAR(10)) as TO_CURRENCY,
	ISNULL(CAST(r.EXCHANGE_RATE AS VARCHAR(20)), '-') as EXCHANGE_RATE,
	ISNULL(CAST(r.INPUT_DATE AS VARCHAR(100)), '-') AS INPUT_DATE
FROM [dbo].[Calendar] c
LEFT JOIN [dbo].[VW_EXCHANGE_RATES_USD] r
	ON c.DATE = r.DATE
	AND R.FROM_CURRENCY = 'USD'
WHERE
	c.DATE <= GETDATE()
