

CREATE VIEW [dbo].[VW_EXCHANGE_RATES_USD_TODAY]
AS
	SELECT
		DATE,
		FROM_CURRENCY, 
		TO_CURRENCY,
		EXCHANGE_RATE
	FROM 
		[dbo].[EXCHANGE_RATES]
	WHERE
		FROM_CURRENCY = 'USD'
		AND DATE = CAST(GETDATE() AS DATE)
