
CREATE VIEW [dbo].[VW_EXCHANGE_RATES_USD_STATISTICS]
WITH SCHEMABINDING
-- aggregates, like MIN() and MAX(), cannot be recomputed just by looking at the data that is being changed
AS
SELECT 
	YEAR(DATE)*100+MONTH(DATE) AS [MONTH], 
	CAST(MIN(EXCHANGE_RATE) AS DECIMAL(12, 6)) AS MIN_EXCHANGE_RATE,
	CAST(MAX(EXCHANGE_RATE) AS DECIMAL(12, 6)) AS MAX_EXCHANGE_RATE,
	CAST(AVG(EXCHANGE_RATE) AS DECIMAL(12, 6)) AS AVG_EXCHANGE_RATE
FROM 
	[dbo].[EXCHANGE_RATES]
WHERE 
	FROM_CURRENCY = 'USD'
GROUP BY 
	YEAR(DATE)*100+MONTH(DATE)
